export const types = [
  { id: 1, name: '新品推荐' },
  { id: 2, name: '元气奶茶系列' },
  { id: 3, name: '柠檬茶' },
  { id: 4, name: '水果茶' },
  { id: 5, name: '小吃' }
]
export const goods = [
  { id: 1, name: '新品1', typeId: 1 },
  { id: 2, name: '新品2', typeId: 1 },
  { id: 3, name: '新品3', typeId: 1 },
  { id: 4, name: '新品4', typeId: 1 },
  { id: 5, name: '新品5', typeId: 1 },
  { id: 6, name: '新品6', typeId: 1 },
  { id: 7, name: '新品7', typeId: 1 },
  { id: 8, name: '新品8', typeId: 1 },
  { id: 9, name: '新品9', typeId: 1 },
  { id: 10, name: '奶茶1', typeId: 2 },
  { id: 11, name: '奶茶2', typeId: 2 },
  { id: 12, name: '奶茶3', typeId: 2 },
  { id: 13, name: '奶茶4', typeId: 2 },
  { id: 14, name: '奶茶5', typeId: 2 },
  { id: 15, name: '奶茶6', typeId: 2 },
  { id: 16, name: '奶茶7', typeId: 2 },
  { id: 17, name: '奶茶8', typeId: 2 },
  { id: 18, name: '柠檬茶1', typeId: 3 },
  { id: 19, name: '柠檬茶2', typeId: 3 },
  { id: 20, name: '柠檬茶3', typeId: 3 },
  { id: 21, name: '柠檬茶4', typeId: 3 },
  { id: 22, name: '柠檬茶5', typeId: 3 },
  { id: 23, name: '柠檬茶6', typeId: 3 },
  { id: 24, name: '柠檬茶7', typeId: 3 },
  { id: 25, name: '柠檬茶8', typeId: 3 },
  { id: 26, name: '柠檬茶9', typeId: 3 },
  { id: 27, name: '柠檬茶10', typeId: 3 },
  { id: 28, name: '水果茶1', typeId: 4 },
  { id: 29, name: '水果茶2', typeId: 4 },
  { id: 30, name: '水果茶3', typeId: 4 },
  { id: 31, name: '水果茶4', typeId: 4 },
  { id: 32, name: '水果茶5', typeId: 4 },
  { id: 33, name: '水果茶6', typeId: 4 },
  { id: 34, name: '水果茶7', typeId: 4 },
  { id: 35, name: '小吃1', typeId: 5 },
  { id: 36, name: '小吃2', typeId: 5 },
  { id: 37, name: '小吃3', typeId: 5 },
  { id: 38, name: '小吃4', typeId: 5 },
  { id: 39, name: '小吃5', typeId: 5 },
  { id: 40, name: '小吃6', typeId: 5 },
  { id: 41, name: '小吃7', typeId: 5 },
  { id: 42, name: '小吃8', typeId: 5 },
  { id: 43, name: '小吃9', typeId: 5 },
  { id: 44, name: '小吃10', typeId: 5 },
  { id: 45, name: '小吃11', typeId: 5 }
]
