export default {
  pages: [
    'pages/index/index',
    'pages/detail/index',
    'pages/store/index',
    'pages/goods/list/index',
    'pages/goods/common/index',
    'pages/refund/apply',
    'pages/refund/type',
    'pages/refund/index',
    'pages/refund/detail',
    'pages/order/post/index',
    'pages/order/post2/index',
    'pages/order/list/index',
    'pages/order/detail/index',
    'pages/mine/auth/index',
    'pages/mine/account/index',
    'pages/mine/nickname/index',
    'pages/mine/setting/index',
    'pages/mine/feedback/index',
    'pages/mine/yue/record',
    'pages/mine/yue/tixian',
    'pages/mine/yue/index',
    'pages/mine/coupon/index',
    'pages/mine/collection/index',
    'pages/mine/attention/index',
    'pages/mine/index',
    'pages/rent/apply',
    'pages/rent/message',
    'pages/rent/order/record/index',
    'pages/rent/order/reject/index',
    'pages/rent/order/confirm/index',
    'pages/rent/order/bill/index',
    'pages/rent/return',
    'pages/rent/detail',
    'pages/rent/index',
    'pages/result/index',
    'pages/address/edit',
    'pages/address/index',
    'pages/order/confirm/index',
    'pages/webview/index',
    'pages/question/index',
    'pages/message/detail',
    'pages/message/index',
    'pages/cart/index',
    'pages/search/index',
    'pages/nearby/index',
    'pages/cate/index',
    'pages/index/cates',
    'pages/bindPhone/index',
    'pages/login/index',
    'pages/temp/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '品租',
    navigationBarTextStyle: 'black'
  }
}
